spring:
  application:
    name: 116fz-doc-generator
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
  liquibase:
    enabled: true
    change-log: classpath:db/changelog/db.changelog-master.yaml

  profiles:
    active: ${SPRING_PROFILES_ACTIVE:local}

server:
  port: ${PORT:8080}

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,env,beans,mappings,prometheus
  endpoint:
    health:
      show-details: always
  info:
    env:
      enabled: true

info:
  app:
    name: 116FZ Document Generator
    version: 1.0.0
    description: Industrial Safety Information System
    author: Dmitry Golikov