spring:
  datasource:
    url: ${POSTGRES_URL:jdbc:postgresql://localhost:5432/PMLLPA}
    username: ${POSTGRES_USER:Admin}
    password: ${POSTGRES_PASSWORD:Dimon678}
    driver-class-name: org.postgresql.Driver

  jpa:
    open-in-view: false

    hibernate:
      ddl-auto: validate

    properties:
      hibernate:
        format_sql: true

    show-sql: true