BEGIN;

  WITH new_org AS (
      INSERT INTO organization (
                                asf_id,
                                organization_full_name,
                                organization_short_name,
                                organization_type_activity
          )
          VALUES (1,
                  'Акционерное общество «Газпром газораспределение Нальчик»',
                  'АО «Газпром газораспределение Нальчик»',
                  'транспортировка газа по трубопроводам, техническое обслуживание и ремонт систем газораспределения, а также проектирование и строительство газовых сетей')
          RETURNING id AS org_id),

       new_object AS (
           INSERT INTO object (
                               org_id,
                               object_city_id,
                               full_name,
                               short_name,
                               hazard_class,
                               hazardous_substance_id,
                               nearest_fire_station,
                               department_gochs_city,
                               emergency_commission
               )
               SELECT org_id,
                      9,
                      'Сеть газоснабжения, в том числе межпоселковая филиала АО «Газпром газораспределение Нальчик» в Урванском районе',
                      'Сеть газоснабжения, в том числе межпоселковая',
                      3,
                      1,
                      'ПСЧ № 1, № 2, № 19 1-й пожарно-спасательный отряд ФПС ГПС ГУ МЧС России по Кабардино-Балкарской Республике',
                      'города Нальчик',
                      'создана'
                 FROM new_org
               RETURNING id AS object_id, org_id),

       new_address AS (
           INSERT INTO object_address (
                                       object_id,
                                       city_name,
                                       raw_address
               )
               SELECT object_id,
                      'г. Нальчик',
                      'г. Нальчик, ул. Новая 3'
                 FROM new_object
               RETURNING object_id),

       update_city AS (
           UPDATE object o
               SET object_city_id = (SELECT oc.id
                                       FROM object_city oc
                                                JOIN object_address oa
                                                     ON LOWER(oa.city_name) LIKE '%' || LOWER(oc.city_name) || '%'
                                      WHERE oa.object_id = o.id
                                      LIMIT 1)
               WHERE o.id IN (SELECT object_id FROM new_object)
               RETURNING o.id),

       new_policy AS (
           INSERT INTO object_insurance_policy (obj_id, number, valid_until)
               SELECT object_id, '12345', '2030-01-01'
                 FROM new_object
               RETURNING obj_id),

       new_balance AS (
           INSERT INTO object_order_minimum_balance (obj_id, number, date)
               SELECT object_id, 10, '2025-01-01'
                 FROM new_object
               RETURNING obj_id)

INSERT
  INTO document_set (org_id, object_id)
SELECT org_id, object_id
  FROM new_object;

COMMIT;

ROLLBACK;

ALTER TABLE object_address
    ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY;

SELECT SETVAL(
               PG_GET_SERIAL_SEQUENCE('object', 'asfId'),
               (SELECT MAX(id) FROM object)
       );

SELECT last_value
  FROM object_id_seq;

DELETE
  FROM object_order_minimum_balance
 WHERE id = 4;

INSERT INTO object_city (id,
                         geo_coords,
                         geo_relief,
                         geo_geology,
                         climat_desc,
                         hydro_desc,
                         infra_transport,
                         infra_engineering,
                         infra_organizations,
                         nearby_towns,
                         mass_people_places,
                         admin_status,
                         dist_centers,
                         city_name)
VALUES (9,
        '43.5558, 43.8504',
        'Предгорная наклонная равнина Кабардино-Балкарии. Высота ~300 м',
        'Чернозёмы выщелоченные, предгорные степи. Сейсмичность — 7-8 баллов',
        'Умеренно-континентальный. Янв -2.8°C, июль +22.4°C. Мягкая зима и жаркое лето',
        'Река Урвань, артезианские скважины, оросительная система',
        'Ж/д станция Докшукино, близость к федеральной трассе Р-217 «Кавказ», автодорога А-158',
        'Урванские районные электросети, газопровод-отвод, ПС 110 кВ Докшукино',
        'АО Газпром газораспределение Нальчик, ОАО Каббалкэнерго',
        'Нальчик (25 км), Майский (20 км), Старый Черек (10 км), Кахун (пригород)',
        'Дом культуры, стадион Химик, церковь Николая Чудотворца, центральная мечеть',
        'Административный центр Урванского района КБР, городское поселение',
        'Крупный центр пищевой промышленности и переработки сельхозпродукции',
        'Нарткала');

DO
$$
    DECLARE
        r RECORD;
    BEGIN
        -- Перебираем все таблицы из вашего списка
        FOR r IN
            SELECT UNNEST(ARRAY [
                'asf', 'asf_certificate', 'asf_composition_deployment_funds', 'asf_document_image',
                'asf_personnel', 'asf_signer', 'asf_specialists', 'asf_work_type',
                'composition_kchs', 'development_accident_scenarios', 'document_set',
                'emergency_services', 'hazardous_param', 'hazardous_param_value',
                'hazardous_substance', 'main_scenarios', 'object', 'object_address',
                'object_city', 'object_image', 'object_insurance_policy',
                'object_order_minimum_balance', 'object_structure', 'object_technological_block',
                'object_type', 'organization', 'organization_address', 'organization_contact',
                'organization_signer', 'primary_fire_extinguishing_equipment',
                'regional_authorities', 'responsible_persons', 'table_title',
                'object_technological_equipment'
                ]) AS tbl_name
            LOOP
                -- Проверяем, есть ли у таблицы колонка 'asfId' и привязанный к ней sequence
                IF EXISTS (SELECT 1
                             FROM information_schema.columns
                            WHERE table_name = r.tbl_name AND column_name = 'asfId') THEN
                    EXECUTE FORMAT(
                            'SELECT setval(pg_get_serial_sequence(%L, %L), coalesce(max(asfId), 1)) FROM %I',
                            r.tbl_name, 'asfId', r.tbl_name
                            );
                END IF;
            END LOOP;
    END
$$;


BEGIN;

  WITH new_org AS (
      INSERT INTO organization (asf_id, organization_full_name, organization_short_name, organization_type_activity)
          VALUES (1,
                  'Акционерное общество «Газпром газораспределение Нальчик»',
                  'АО «Газпром газораспределение Нальчик»',
                  'транспортировка газа по трубопроводам, техническое обслуживание и ремонт систем газораспределения, а также проектирование и строительство газовых сетей')
          RETURNING id AS org_id),

       new_org_address AS (
           INSERT INTO organization_address (organization_id, index, constituent_entity, city_name, street, house)
               SELECT org_id,
                      '360001',
                      'Кабардино-Балкарская Республика',
                      'г. Нальчик',
                      'ул. Арманд',
                      '30'
                 FROM new_org
           --RETURNING org_id
       ),

       new_org_contact AS (
           INSERT INTO organization_contact (organization_id, full_name, position, phones, address)
               SELECT new_org.org_id, value.name, value.pos, value.phon, value.address
                 FROM new_org
                          CROSS JOIN (VALUES (NULL, 'Диспетчер ЦДС', '8 (8662) 40-12-38',
                                              'г. Нальчик, ул. И. Арманд 30'),
                                             ('Кудаев А.Б.', 'Директор филиала', '8 (905) 436-58-58',
                                              'г. Нальчик, ул. Масаева 12'),
                                             ('Шогенов А.В.', 'Главный инженер', '8 (930) 427-13-15',
                                              'г. Нальчик, ул. Интернациональная 39'),
                                             ('Язиев А.Н.', 'Начальник АДС ', '8 (906) 484-83-09',
                                              'г. Нарткала, ул. О. Кошевого 5, кв.38.'),
                                             ('Джаппуев Э.М.', 'Инженер по ПБ', '8 (930) 798-34-89',
                                              'с. Яникой, Пушкина 70'),
                                             ('Калибатова М.С.', 'Специалист по ОТ', '8 (903) 492-62-95',
                                              'г. Нарткала, ул. Шекихачевой 6, кв.76.')) AS value (name, pos, phon, address)
           -- RETURNING org_id
       ),

       new_org_signer AS (
           INSERT INTO organization_signer (org_id, signer_position, signer_surname_basic)
               SELECT org_id,
                      'Генеральный директор',
                      'Вороков З.В.'
                 FROM new_org
               RETURNING org_id),

       new_object AS (
           INSERT INTO object (
                               org_id,
                               object_city_id,
                               full_name,
                               short_name,
                               hazard_class,
                               hazardous_substance_id,
                               nearest_fire_station,
                               department_gochs_city,
                               emergency_commission
               )
               SELECT org_id,
                      9,
                      'Сеть газоснабжения, в том числе межпоселковая филиала АО «Газпром газораспределение Нальчик» в Урванском районе',
                      'Сеть газоснабжения, в том числе межпоселковая',
                      3,
                      1,
                      'ПСЧ № 1, № 2, № 19 1-й пожарно-спасательный отряд ФПС ГПС ГУ МЧС России по Кабардино-Балкарской Республике',
                      'города Нарткала',
                      'создана'
                 FROM new_org
               RETURNING id AS object_id, org_id),

       new_address AS (
           INSERT INTO object_address (object_id, constituent_entity, area_hierarchy, coordinates)
               SELECT object_id,
                      'КБР',
                      'Урванский район',
                      '43°33''18.0"N 43°51''00.0"E'
                 FROM new_object
               RETURNING object_id),

       new_policy AS (
           INSERT INTO object_insurance_policy (obj_id, number, valid_until)
               SELECT object_id, 'GAZX12579825375000', '2026-12-23'
                 FROM new_object
               RETURNING obj_id),

       new_balance AS (
           INSERT INTO object_order_minimum_balance (obj_id, number, date)
               SELECT object_id, 24, '2026-02-09'
                 FROM new_object
               RETURNING obj_id),

       new_substance AS (
           INSERT INTO hazardous_substance (object_id, name, name_gen)
               SELECT object_id, 'природный газ', 'природного газа'
                 FROM new_object
               RETURNING object_id),

       new_type AS (
           INSERT INTO object_type (object_id, object_type_definitions)
               SELECT object_id,
                      'технологический комплекс, состоящий из наружных газопроводов (включая межпоселковые), сооружений, технических и технологических устройств, предназначенный для транспортировки газа от источника до сети газопотребления'
                 FROM new_object
               RETURNING object_id),

       new_kchs AS (
           INSERT INTO composition_kchs (object_id, number, position, full_name, cell_phone, home_address)
               SELECT new_object.object_id, ROW_NUMBER() OVER () AS num, value.pos, value.name, value.phone, value.addr
                 FROM new_object
                          CROSS JOIN (VALUES ('Председатель КЧС и ПБ', 'Директор филиала № 4 Кудаев А.Б.',
                                              '8 (905) 436-58-58', 'г. Нальчик ул. Масаева 12'),
                                             ('Зам. председателя КЧС и ПБ',
                                              'Главный инженер филиала № 4 Шогенов А.В.', '8 (930) 427-13-15',
                                              '. Нальчик ул. Интернациональная 39'),
                                             ('Член КЧС и ПБ', 'Зам. директора филиала № 4 Шалов С.К.',
                                              '8 (999) 035-40-06', 'г. Нальчик ул. Тарчёкова  19 корпус А кв. 4'),
                                             ('Член КЧС и ПБ', 'Начальник ПТО филиала №4 Тенов А.В.',
                                              '8 (903) 495-51-61', 'с. Нижний Черек ул. Кагазежева 127'),
                                             ('Член КЧС и ПБ', 'Начальник АДС филиала № 4 Язиев А.Н.',
                                              '8 (906) 484-83-09',
                                              'г. Нарткала ул. О. Кошевого 5 кв. 38')) AS value(pos, name, phone, addr)
               RETURNING object_id),

       new_structure AS (
           INSERT INTO object_structure (object_id, name, num)
               SELECT new_object.object_id, value.name, ROW_NUMBER() OVER () AS num
                 FROM new_object
                          CROSS JOIN (VALUES ('Участок газопровода высокого давления'),
                                             ('Участок газопровода среднего давления')) AS value(name)
               RETURNING object_id),

       new_techno AS (
           INSERT INTO object_technological_block (object_id, name, num)
               SELECT object_id, 'Газопроводы;', 1
                 FROM new_object
               RETURNING object_id),

       new_image AS (
           INSERT INTO object_image (object_id, image_blob, caption, link_text, group_key)
               SELECT new_object.object_id,
                      src.image_blob,
                      src.caption,
                      src.link_text,
                      src.group_key
                 FROM new_object
                          CROSS JOIN (SELECT image_blob, caption, link_text, group_key
                                        FROM object_image
                                       WHERE id = 4) AS src
               RETURNING object_id),

       new_equpment AS (
           INSERT INTO primary_fire_extinguishing_equipment (object_id, num, name_product, quantity, location)
               SELECT new_object.object_id, ROW_NUMBER() OVER () AS num, value.name, value.quantity, value.location
                 FROM new_object
                          CROSS JOIN (VALUES ('Багры', '2', 'Пожарный щит'),
                                             ('Лопаты', '2', 'Пожарный щит'),
                                             ('Ломы', '2', 'Пожарный щит'),
                                             ('Топор', '1', 'Пожарный щит'),
                                             ('Рукава пожарные', '1', 'Пожарный щит'),
                                             ('Сопла пожарные', '1', 'Пожарный щит'),
                                             ('Ведра', '2', 'Пожарный щит'),
                                             ('Спец. одежда', '4', 'Склад'),
                                             ('Рукавицы', '10', 'Склад'),
                                             ('Огнетушители ОУ-5', '2', 'Пожарный щит'),
                                             ('Ящик с песком', '1', 'Пожарный щит'),
                                             ('Противопожарное полотно', '1',
                                              'Пожарный щит')) AS value(name, quantity, location)
               RETURNING object_id),

       new_authorities AS (
           INSERT INTO regional_authorities (object_id, name, department, phone_number, address)
               SELECT new_object.object_id, value.name, value.department, value.phone, value.address
                 FROM new_object
                          CROSS JOIN (VALUES ('Северо-Кавказское межрегиональное управление Росприроднадзора по Кабардино-Балкарской Республике',
                                              NULL, '8 (967) 415-99-31', NULL),
                                             ('Главное управление МЧС России по Кабардино-Балкарской Республике',
                                              'Приемная', '8 (8662) 74-03-23',
                                              '360017, КБР, г.о. Нальчик, ул. Чернышевского, д. 19'),
                                             ('Кавказское управление Ростехнадзора', 'Приемная',
                                              E'8 (8793) 34-64-24\n8 (928) 307-04-62',
                                              'Ставропольский край, г. Железноводск, пос. Иноземцево, тер. СНТ Машук-2, ул. Ореховая д. 6'),
                                             ('Структурное подразделение по Кабардино-Балкарской Республике',
                                              'Приемная', '8 (8662) 91-99-33',
                                              '360019, Кабардино-Балкарская Республика, г. Нальчик,  ул. Киримова, 136')) AS value(name, department, phone, address)
               RETURNING object_id),

       new_persons AS (
           INSERT INTO responsible_persons (object_id, number, full_name, position)
               SELECT new_object.object_id, ROW_NUMBER() OVER () AS number, value.name, value.position
                 FROM new_object
                          CROSS JOIN (VALUES ('Шогенов А.В.', 'Главный инженер'),
                                             ('Язиев А.Н.', 'Начальник АДС'),
                                             ('Тхазеплов М.М.', 'Начальник СЭГС'),
                                             ('Джаппуев Э.М.', 'Инженер по ПБ'),
                                             ('Калибатова М.С.', 'Специалист по ОТ')) AS value(name, position)
               RETURNING object_id),

       new_equipment AS (
           INSERT INTO object_technological_equipment (num, equipment_name, characteristics, object_id)
               SELECT ROW_NUMBER() OVER () AS num, value.name, value.characteristics, new_object.object_id
                 FROM new_object
                          CROSS JOIN (VALUES (E'Участок газопровода\nвысокого давления',
                                              E'Общая длнна - 69,520 км.\n' ||
                                              E'Надземный - 0,868 км.\nПодземный - 68,562 км.\nPmax - 0,6 \nОпасное вещество - Мпа.\nМатериал изготовления - ' ||
                                              E'сталь (мм): 57, 76, 89, 102, 108, 114, 159, 168, 219, 273, 325.\nМатериал изготовления - ПЭ (мм): 60, 90, 110.\n' ||
                                              E'Вид опасного вещества - воспламеняющийся и горючий газ\nДата ввода в эксплуатацию - 1973 - 03.2023 г.'),
                                             (E'Участок газопровода\nвысокого давления',
                                              E'Общая длнна - 28,583 км.\n' ||
                                              E'Надземный - 0,138 км.\nПодземный - 28,445 км.\nPmax - 0,6 \nОпасное вещество - Мпа.\nМатериал изготовления - ' ||
                                              E'сталь (мм): 57, 76, 89, 102, 114, 159, 219.\nВид опасного вещества - воспламеняющийся и горючий газ\nДата ввода ' ||
                                              E'в эксплуатацию - 1972 - 03.2023 г.')) AS value(name, characteristics)
               RETURNING object_id)

INSERT
  INTO document_set (org_id, object_id)
SELECT org_id, object_id
  FROM new_object;

COMMIT;

--команды для переноса бд
--создание дампа
--docker exec -t DocumentsDB pg_dump -U Admin -f /backup.sql PMLLPA
--перенос на гугл диск
--docker cp DocumentsDB:/backup.sql "J:\Google диск\Програмирование\Java\db\backup.sql"
--очищаем временный контейнер
-- docker exec -t DocumentsDB rm /backup.sql

--запись данных в контейнер из дампа
--docker cp "F:\Google диск\Програмирование\Java\db\backup.sql" DocumentsDB:/backup.sql
--записываем в уже созданный контейнер
--docker exec -it newDocumentsDB psql -U Admin -d PMLLPA -f /backup.sql
--очищаем временный контейнер
--docker exec -it newDocumentsDB rm /backup.sql

DO $$
    DECLARE
        t_name TEXT;
        table_list TEXT[] := ARRAY[
            'asf', 'asf_certificate', 'asf_composition_deployment_funds',
            'asf_document_image', 'asf_personnel', 'asf_signer',
            'asf_specialists', 'asf_work_type', 'emergency_services',
            'hazardous_param', 'hazardous_param_value', 'hazardous_substance',
            'object', 'object_address', 'object_city', 'object_composition_kchs',
            'object_development_accident_scenarios', 'object_image',
            'object_insurance_policy', 'object_main_scenarios',
            'object_order_minimum_balance', 'object_primary_fire_extinguishing_equipment',
            'object_regional_authorities', 'object_responsible_persons',
            'object_structure', 'object_technological_block',
            'object_technological_equipment', 'object_type', 'organization',
            'organization_address', 'organization_contact', 'organization_signer',
            'table_title'
            ];
    BEGIN
        FOREACH t_name IN ARRAY table_list LOOP
                EXECUTE format(
                        'SELECT setval(pg_get_serial_sequence(''public.%I'', ''id''), COALESCE(MAX(id), 0) + 1, false) FROM public.%I',
                        t_name, t_name
                        );
            END LOOP;
    END $$;

