package com.caseo.app;

import com.caseo.domain.repository.*;

record RepositoryContext (AsfRepository asfRepository ,AsfSignerRepository asfSignerRepository,
AsfWorkTypeRepository asfWorkTypeRepository,DocumentSetRepository documentSetRepository,
HazardousParamRepository hazardousParamRepository, HazardousParamValueRepository hazardousParamValueRepository,
HazardousSubstanceRepository hazardousSubstanceRepository, ObjectRepository objectRepository,
ObjectStructureRepository objectStructureRepository, ObjectCityRepository objectCityRepository,
ObjectAddressRepository objectAddressRepository, ObjectTypeRepository objectTypeRepository,
ObjectInsurancePolicyRepository objectInsurancePolicyRepository, ObjectOrderMinimumBalanceRepository objectOrderMinimumBalanceRepository,
OrganizationRepository organizationRepository, OrganizationSignerRepository organizationSignerRepository,
TechnologicalEquipmentRepository technologicalEquipmentRepository,TechnologicalBlockRepository technologicalBlockRepository) {
}
