package com.caseo.app;

import com.caseo.domain.repository.*;

record RepositoryContext(
        ObjectAccidentScenariosRepository objectAccidentScenariosRepository,
        AsfCertificateRepository asfCertificateRepository,
        AsfCompositionDeploymentFundsRepository asfCompositionDeploymentFundsRepository,
        AsfDocumentImageRepository asfDocumentImageRepository,
        AsfPersonnelRepository asfPersonnelRepository,
        AsfRepository asfRepository,
        AsfSignerRepository asfSignerRepository,
        AsfSpecialistsRepository asfSpecialistsRepository,
        AsfWorkTypeRepository asfWorkTypeRepository,
        ObjectCompositionKchsRepository objectCompositionKchsRepository,
        DocumentSetRepository documentSetRepository,
        ReferenceEmergencyServicesRepository referenceEmergencyServicesRepository,
        ObjectFireEquipmentRepository objectFireEquipmentRepository,
        ObjectHazardousParamRepository objectHazardousParamRepository,
        ObjectHazardousParamValueRepository objectHazardousParamValueRepository,
        ObjectHazardousSubstanceRepository objectHazardousSubstanceRepository,
        ObjectMainScenariosRepository objectMainScenariosRepository,
        ObjectRepository objectRepository,
        ObjectStructureRepository objectStructureRepository,
        ReferenceCityRepository referenceCityRepository,
        ObjectAddressRepository objectAddressRepository,
        ReferenceTableTitleRepository referenceTableTitleRepository,
        ObjectTypeRepository objectTypeRepository,
        ObjectImageRepository objectImageRepository,
        ObjectInsurancePolicyRepository objectInsurancePolicyRepository,
        ObjectOrderMinimumBalanceRepository objectOrderMinimumBalanceRepository,
        OrganizationAddressRepository organizationAddressRepository,
        OrganizationContactRepository organizationContactRepository,
        OrganizationRepository organizationRepository,
        OrganizationSignerRepository organizationSignerRepository,
        ObjectPersonsResponsibleRepository objectPersonsResponsibleRepository,
        ObjectRegionAuthoritiesRepository objectRegionAuthoritiesRepository,
        ObjectTechnologicalEquipmentRepository objectTechnologicalEquipmentRepository,
        ObjectTechnologicalBlockRepository objectTechnologicalBlockRepository
) {
}
